### PR TITLE
Fix Tag alpha bugs and add tests

### LINKED ISSUE #146: No constraints on word count for `Tag` may lead to overflow which can potentially cause crashes
Perhaps we should set an upper limit for the word count of Tags

### LINKED ISSUE #147: `Tag` allows white space but does not handle extra white space
If there is extra white space in a Tag, for example typing Table              Tennis, it is saved as such. Would it better to trim the extra white spaces?

### LINKED ISSUE #149: No upper limit on number of `Tag`s
This may lead to overflow and cause crashes in case of malicious use

### PR DESCRIPTION
**Pull request by SeanFoongjt**
Fixes #149 
Fixes #147 
Fixes #146

### CODE REVIEW

File: src/main/java/seedu/address/model/tag/Tag.java [hunk 1]
```diff
@@ -10,8 +10,9 @@
 public class Tag {
 
     public static final String MESSAGE_CONSTRAINTS = "Tags names should be alphanumeric and can have spaces, but "
-            + "cannot be empty";
-    public static final String VALIDATION_REGEX = "\\p{Alnum}[\\p{Alnum}\\p{Zs}]*";
+            + "cannot be empty or exceed 100 characters";
+    public static final String MAX_TAGS_CONSTRAINTS = "A person should only have up to 10 tags.";
+    public static final String VALIDATION_REGEX = "\\p{Alnum}[\\p{Alnum}\\p{Zs}]{0,99}";
```
Comment (EdaYeo) [inline src/main/java/seedu/address/model/tag/Tag.java:15]: Would {0,99} regex mean allowing 0-99 characters instead of 1-100 characters? Should it be {1, 100} instead?

**Review by EdaYeo — COMMENTED** [review]
LGTM except for one question about number of characters in regex!

**Review by EdaYeo — APPROVED** [review]

File: src/main/java/seedu/address/model/tag/Tag.java (hunk 1 above)
Comment (SeanFoongjt) [reply src/main/java/seedu/address/model/tag/Tag.java:15]: The Alnum in front is already 1 character, so on top of that it should be 0 to 99 characters. This should be correct.
